CREATE TABLE IF NOT EXISTS SPRING_SESSION (
	PRIMARY_ID CHAR(36) NOT NULL,
	SESSION_ID CHAR(36) NOT NULL,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	EXPIRY_TIME BIGINT NOT NULL,
	PRINCIPAL_NAME VARCHAR(100),
	CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE IF NOT EXISTS SPRING_SESSION_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(36) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES LONGVARBINARY NOT NULL,
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USERS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  ENABLED BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTHORITIES (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  AUTHORITY VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPLOYEE (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_USERNAME ON USERS(USERNAME);
CREATE INDEX IF NOT EXISTS IDX_AUTHORITY ON AUTHORITIES(AUTHORITY);
CREATE INDEX IF NOT EXISTS IDX_EMPLOYEE_FIRST_NAME_LAST_NAME ON EMPLOYEE(FIRST_NAME, LAST_NAME);
CREATE INDEX IF NOT EXISTS IDX_EMAIL ON EMPLOYEE(EMAIL);

INSERT INTO USERS (ID, USERNAME, PASSWORD, ENABLED)
 SELECT 1, 'admin', '$2a$10$3Zz9Zz9Zz9Zz9Zz9Zz9Zu1', true
 WHERE NOT EXISTS (SELECT USERNAME FROM USERS WHERE USERNAME = 'admin');
INSERT INTO USERS (ID, USERNAME, PASSWORD, ENABLED)
  SELECT 2, 'user', '$2a$10$3Zz9Zz9Zz9Zz9Zz9Zz9Zu1', true
  WHERE NOT EXISTS (SELECT USERNAME FROM USERS WHERE USERNAME = 'user');
INSERT INTO AUTHORITIES (ID, AUTHORITY)
  SELECT 1, 'ROLE_ADMIN'
  WHERE NOT EXISTS (SELECT AUTHORITY FROM AUTHORITIES WHERE AUTHORITY = 'ROLE_ADMIN');
INSERT INTO AUTHORITIES (ID, AUTHORITY)
  SELECT 2, 'ROLE_USER'
  WHERE NOT EXISTS (SELECT AUTHORITY FROM AUTHORITIES WHERE AUTHORITY = 'ROLE_USER');
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL)
  SELECT 1, 'John', 'Doe', 'john@email.com'
  WHERE NOT EXISTS (SELECT ID FROM EMPLOYEE WHERE  ID=1);
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL)
  SELECT 2, 'Jane', 'Doe', 'jane@email.com'
  WHERE NOT EXISTS (SELECT ID FROM EMPLOYEE WHERE ID=2);